name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
      
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `Types.Core`
        run: dotnet build "${{ github.event.repository.name }}/core" -c Debug /p:Version=${VERSION}
      
      - name: Build `Types.Core`
        run: dotnet build "${{ github.event.repository.name }}/core" -c Release /p:Version=${VERSION}
      
      - name: Build `Types.Generator`
        run: dotnet build "${{ github.event.repository.name }}/generator" -c Debug /p:Version=${VERSION}
      
      - name: Build `Types.Generator`
        run: dotnet build "${{ github.event.repository.name }}/generator" -c Release /p:Version=${VERSION}
      
      - name: Build `Types`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Debug /p:Version=${VERSION}
      
      - name: Build `Types`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
      - name: Build `Types.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Debug /p:Version=${VERSION}
      
      - name: Build `Types.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Release /p:Version=${VERSION}
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Release --logger "trx"
            
      - name: Pack `Types.Core`
        run: dotnet pack "${{ github.event.repository.name }}/core" /p:Version=${VERSION} --no-build --output .
      
      - name: Pack `Types.Generator`
        run: dotnet pack "${{ github.event.repository.name }}/generator" /p:Version=${VERSION} --no-build --output .
      
      - name: Pack `Types`
        run: dotnet pack "${{ github.event.repository.name }}/source" /p:Version=${VERSION} --no-build --output .

      - name: Add GitHub source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `Types.Core` to GitHub registry
        run: dotnet nuget push SimulationTree.Types.Core.${VERSION}.nupkg --source github --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_GITHUB }}
      
      - name: Publish `Types.Core` to official registry
        run: dotnet nuget push SimulationTree.Types.Core.${VERSION}.nupkg --source nuget.org --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_OFFICIAL }}
      
      - name: Publish `Types.Generator` to GitHub registry
        run: dotnet nuget push SimulationTree.Types.Generator.${VERSION}.nupkg --source github --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_GITHUB }}
      
      - name: Publish `Types.Generator` to official registry
        run: dotnet nuget push SimulationTree.Types.Generator.${VERSION}.nupkg --source nuget.org --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_OFFICIAL }}
      
      - name: Publish `Types` to GitHub registry
        run: dotnet nuget push SimulationTree.Types.${VERSION}.nupkg --source github --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_GITHUB }}
      
      - name: Publish `Types` to official registry
        run: dotnet nuget push SimulationTree.Types.${VERSION}.nupkg --source nuget.org --api-key ${API_KEY}
        env:
          API_KEY: ${{ secrets.NUGET_TOKEN_OFFICIAL }}